apiVersion: apps/v1
kind: Deployment
metadata:
  name: vueserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        editor: vscode
        app: front
    spec:
      containers:
      - name: vueserver
        image: freitas29/vuejsapp
        ports:
          - containerPort: 80